# Generated by Django 2.1 on 2018-09-30 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('picture_url', models.URLField(max_length=500)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=5000)),
                ('category', models.CharField(max_length=1000)),
                ('date_added', models.DateField(blank=True, default=datetime.datetime.now)),
                ('paypal_button', models.CharField(max_length=5000)),
            ],
        ),
    ]
